"""empty message

Revision ID: 5ac227d891ad
Revises: 0aeee691cc9b
Create Date: 2017-08-21 01:32:00.850703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ac227d891ad'
down_revision = '0aeee691cc9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=64), nullable=True),
    sa.Column('url_t', sa.String(length=64), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('posts', sa.Column('author_id', sa.Integer(), nullable=True))
    op.drop_constraint('posts_User_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    op.drop_column('posts', 'User')
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.drop_constraint('users_Role_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    op.drop_column('users', 'Role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('Role', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_Role_fkey', 'users', 'roles', ['Role'], ['id'])
    op.drop_column('users', 'role_id')
    op.add_column('posts', sa.Column('User', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_User_fkey', 'posts', 'users', ['User'], ['id'])
    op.drop_column('posts', 'author_id')
    op.drop_table('images')
    # ### end Alembic commands ###
