"""empty message

Revision ID: b6be86af662d
Revises: 5ac227d891ad
Create Date: 2017-08-22 23:46:14.722265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6be86af662d'
down_revision = '5ac227d891ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('activation', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'activation')
    # ### end Alembic commands ###
