"""empty message

Revision ID: c7afd61699e8
Revises: d64257bc8ce1
Create Date: 2017-08-16 15:07:04.257037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7afd61699e8'
down_revision = 'd64257bc8ce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('Role', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['Role'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'Role')
    # ### end Alembic commands ###
